name: Trigger auto deployment for cntrapp-synai-demo001-sec-fetc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cntrapp-synai-demo001-sec-fetc-AutoDeployTrigger-645ae94f-d47e-4472-a915-8a70ca5dcc9f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CNTRAPPSYNAIDEMO001SECFETC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CNTRAPPSYNAIDEMO001SECFETC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CNTRAPPSYNAIDEMO001SECFETC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.CNTRAPPSYNAIDEMO001SECFETC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CNTRAPPSYNAIDEMO001SECFETC_REGISTRY_PASSWORD }}
          containerAppName: cntrapp-synai-demo001-sec-fetc
          resourceGroup: synai-demo001-rg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


